language: python
python:
  - "2.7"
install: 
  - "pip install -r requirements-ci.txt --use-mirrors"
script: nosetests --with-coverage --cover-erase --cover-inclusive --cover-branches --cover-package=bigtempo
after_success:
  - coveralls